### ISSUE TITLE
README & Docs

### ISSUE THREAD

**Issue by coolaj86** [Dream-Team99/Instasham-server#21]
How would I install this?

What are the deps?

What are the command line options and config files for ports, api keys, etc?

**Comment by alangford** [comment]
It's set up on a Postgres server and the app is running through android studio.

I unfortunately can't give you the config file with the keys because of security issues.

but you can clone the server repo and the app repo, and set up a aws s3 bucket and a database for it.

**Comment by alangford** [comment]
All the dependencies are listed in the require variables on the sever and the dependencies for the app are listed in the JSON file.
